config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :resources
  get 'hello_world', to: 'hello_world#index'
  # Redirect www to non-www.
  if ENV['CANONICAL_HOST']
    constraints(host: Regexp.new("^(?!#{Regexp.escape(ENV['CANONICAL_HOST'])})")) do
      match '/(*path)' => redirect { |params, req| "https://#{ENV['CANONICAL_HOST']}/#{params[:path]}" },  via: [ :get, :post, :put, :delete ]
    end
  end

  root 'home#index'

  get '/about', to: 'home#about', as: 'about'

  # get '/resources', to: 'home#resources', as: 'resources'

  # get '/guidelines', to: 'appointments#guidelines', as: 'guidelines'

  # get '/data/appointments',   to: 'data#appointments'
  get '/data/requests',   to: 'data#requests'
  get '/data/users',      to: 'data#users'
  get '/data/patients', to: 'data#patients'

  # get '/reports', to: "reports#index"

  get '/admin' => 'reports#index'
  # get '/admin/edit' => 'admin#edit_site', as: 'edit_site'
  # post '/admin/edit' => 'admin#edit_site'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/p/:page' => 'users/registrations#index', as: 'users_with_pagination'
    get 'users', to: 'users/registrations#index', as: 'patients'
    # get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end

  # get '/appointments/p/:page' => 'appointments#index', as: 'appointments_with_pagination'
  get '/requests/p/:page' => 'requests#index', as: 'requests_with_pagination'

  delete '/images/:resource_name/:resource_id', to: 'images#destroy'

  # resources :appointments do
  #   collection do
  #     get :requested
  #     get :own
  #   end

  #   member do
  #     post :toggle_patient
  #     post :completed_patient
  #     get :patients
  #   end
  # end

  resources :requests do
    collection do
      get :requested
      get :own
    end

    member do
      post :toggle_patient
      post :completed_patient
      post :confirm_appointment
      post :mark_as_unbooked
      post :mark_as_in_progress
      post :mark_as_book_complete
      get :patients
    end
  end

  scope 'admin' do
    post :delete_user, to: 'admin#delete_user', as: 'delete_user'
    post :toggle_highlight, to: 'admin#toggle_highlight', as: 'toggle_request_highlight'
  end


  get '/:category_slug(/p/:page)', to: 'requests#index', action: :index


end

app/models/request.rb
class Request < ApplicationRecord
    include HasCoverPhoto
    include PgSearch::Model
  
    belongs_to :user
    has_many :appointments, dependent: :destroy
  
    validates :f_name, presence: true
    validates :l_name, presence: true
    # validates :short_description, length: { maximum: 129 }
    # validate :must_have_one_skill, on: :create
    # validate :date_order, on: :create
  
    has_many :patients, dependent: :destroy
    has_many :requested_users, through: :patients, source: :user, dependent: :destroy
  
    acts_as_taggable_on :weekdays
    acts_as_taggable_on :weekends
    acts_as_taggable_on :request_types
    acts_as_taggable_on :locations
    acts_as_taggable_on :weekday_times
    acts_as_taggable_on :weekend_times
    acts_as_taggable_on :skills  
    acts_as_taggable_on :categories  

  
    pg_search_scope :search, against: %i(name description participants looking_for patient_location target_country target_location highlight)
  
    after_save do
      # expire homepage caches if they contain this request
      Settings.request_categories.each do |category|
        cache_key = "request_category_#{category[:name].downcase}_featured_requests"
        featured_requests = Rails.cache.read cache_key
  
        next if featured_requests.blank?
  
        Rails.cache.delete(cache_key) if featured_requests.map(&:id).include? self.id
      end
    end
  
    # validates :status, inclusion: { in: Settings.request_statuses }
  
    # before_validation :default_values
  
    # def default_values
    #   self.status = Settings.request_statuses.first if self.status.blank?
    # end
  
    def to_param
      [id, f_name.parameterize, l_name.parameterize].join('-')
    end
  
    def can_edit?(edit_user)
      edit_user && (self.user == edit_user || edit_user.is_coach?)
    end
  
    def patient_emails
      self.requested_users.collect { |u| u.email }
    end
  
    def requested_users_count
      requested_users.count
    end
  
    def serializable_hash(options = {})
      super(
        only: [
          :id,
          :name,
          :description,
          :participants,
          :goal,
          :looking_for,
          :patient_location,
          :target_country,
          :target_location,
          :contact,
          :highlight,
          :progress,
          :docs_and_demo,
          :number_of_patients,
          :accepting_patients,
          :created_at,
          :updated_at,
          :status,
          :short_description
        ],
        methods: [:to_param, :requested_users_count, :request_type_list, :location_list, :category_list, :skill_list]
      )
    end
  
    def must_have_one_skill
      errors.add(:base, 'You must select at least one skill') if self.skill_list.all?{|skill| skill.blank? }    
    end
  
    def date_order
      if self.end_date_recurring != true
        if self.end_date != ''
          errors.add(:base, 'End date must be after start date') if Date.parse(self.start_date) > Date.parse(self.end_date)
        elsif self.end_date == ''
          errors.add(:base, 'You must provide an end date or select "Recurring"')
        end 
      end
    end
  
    def category
      request_categories = {}
      begin
        Settings.request_categories.each do |category|
          intersection = self.request_type_list.to_a & category['request_types'].to_a
          request_categories[category.name] = intersection.count
        end
  
        present_category = request_categories.sort_by { |k, v| v }.reverse.first.first
      end
  
      present_category
    end
  
    def cover_photo(category_override = nil)
      Rails.cache.fetch(cdn_image_cache_key, expires_in: 1.month) do
  
        if self.image.present?
          cdn_variant(resize_to_limit: [600, 600])
        else
          # FIXME use slug of category instead? and fallback if this is missing
          filename = category_override.blank? ? self.category.downcase.gsub(' ', '-') : category_override.downcase
  
          # There is no `image_pack_path` -- see https://github.com/rails/webpacker/issues/2562
          ActionController::Base.helpers.asset_pack_path "media/images/#{filename}-default.png"
        end
      end
    end
  
    def self.get_featured_requests
      requests_count = Settings.homepage_featured_requests_count
      Request.where(highlight: true).includes(:request_types, :categories, :locations, :skills, :patients).limit(requests_count).order('RANDOM()')
    end
end
  

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy, :toggle_patient, :completed_patient, :requested, :own, :patients ]
    before_action :set_request, only: [ :show, :edit, :update, :destroy, :toggle_patient, :completed_patient, :patients ]
    before_action :ensure_owner_or_admin, only: [ :edit, :update, :destroy, :patients ]
    before_action :set_filters_open, only: :index
    before_action :set_requests_query, only: :index
    before_action :hydrate_request_categories, only: :index
    before_action :ensure_no_legacy_filtering, only: :index
    before_action :set_bg_white, only: [:index, :own, :requested]
  
    def index
      params[:page] ||= 1
      @show_filters = true
      @show_search_bar = true
      @show_sorting_options = true
      @show_global_announcements = false
      @applied_filters = params.dup
  
      if request.path != requests_path and params[:category_slug].present?
        @request_category = Settings.request_categories.find { |category| category.slug == params[:category_slug] }
        #byebug
        raise ActionController::RoutingError, 'Not Found' if @request_category.blank? && @request_location.blank?
  
        if @request_category.present?
          @applied_filters[:request_types] = @request_category[:request_types]
          @featured_requests = Rails.cache.read "request_category_#{@request_category[:name].downcase}_featured_requests"
          @requests = @requests.tagged_with(params[:category_slug], any: true, on: :categories) if params[:category_slug].present?
          #byebug
        end
  
        if @request_location.present?
          @applied_filters[:request_types] = @request_location[:request_types]
          @featured_requests = Rails.cache.read "request_category_#{@request_location[:name].downcase}_featured_requests"
          @requests = @requests.tagged_with(params[:category_slug], any: true, on: :locations) if params[:category_slug].present?
          #byebug
        end
      
      else
        @featured_requests = Request.get_featured_requests
      end
  
      respond_to do |format|
        format.html do
          @requests_header = I18n.t('requests_looking_for_patients')
          @requests_subheader = I18n.t('new_or_established_requests_helping_with')
          @page_title = I18n.t('all_requests')
  
          @requests = @requests.page(params[:page]).per(24)
  
          @index_from = (@requests.prev_page || 0) * @requests.limit_value + 1
          @index_to = [@index_from + @requests.limit_value - 1, @requests.total_count].min
          @total_count = @requests.total_count
        end
        format.json do
          render json: @requests
        end
      end
    end
  
    def requested
      params[:page] ||= 1
  
      @requests = current_user.requests.page(params[:page]).per(25)
      @index_from = (@requests.prev_page || 0) * @requests.limit_value + 1
      @index_to = [@index_from + @requests.limit_value - 1, @requests.total_count].min
  
      @requests_header = I18n.t('requested_requests')
      @requests_subheader = I18n.t('these_are_the_requests_where_you_requested')
      @page_title = I18n.t('requested_requests')
      render action: 'index'
    end
  
    def own
      params[:page] ||= 1
  
      @requests = current_user.requests.page(params[:page]).per(25)
  
      @index_from = (@requests.prev_page || 0) * @requests.limit_value + 1
      @index_to = [@index_from + @requests.limit_value - 1, @requests.total_count].min
  
      @requests_header = I18n.t('own_requests')
      @requests_subheader = I18n.t('these_are_the_requests_you_created')
      @page_title = I18n.t('own_requests')
      render action: 'index'
    end
  
    def show
      respond_to do |format|
        format.html
        format.json { render json: @request }
      end
    end
  
    def patients
      respond_to do |format|
        format.csv { send_data @request.requested_users.to_csv, filename: "patients-#{Date.today}.csv" }
      end
    end
  
    def new
      @request = Request.new
      track_event 'Request creation started'
    end
  
    def create
      @request = current_user.requests.new(request_params)
      # @request.weekday_avail = @request.weekday_list.join(".").to_s
      # @request.weekday_times = @request.weekday_time_list.join(".").to_s
      # @request.weekend_avail = @request.weekend_list.join(".").to_s
      # @request.weekend_times = @request.weekend_time_list.join(".").to_s
      respond_to do |format|
        if @request.save
          track_event 'Request creation complete'
          Patient.create(user_id: current_user.id, request_id: @request.id, f_name: @request.f_name, l_name: @request.l_name, email: @request.patient_email, phone: @request.phone)
          # byebug
          # RequestMailer.with(request: @request).new_request.deliver_now
          format.html { redirect_to @request, notice: I18n.t('request_was_successfully_created') }
          format.json { render :show, status: :created, location: @request }
        else
          format.html { render :new }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def edit
    end
  
    def update
      updated = @request.update(request_params)
  
      respond_to do |format|
        if updated
          format.html { redirect_to @request, notice: I18n.t('request_was_successfully_updated') }
          format.json { render :show, status: :ok, location: @request }
        else
          format.html { render :edit }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @request.destroy
      respond_to do |format|
        format.html { redirect_to requests_url, notice: I18n.t('request_was_successfully_deleted') }
        format.json { head :no_content }
      end
    end
  
    def toggle_patient
      if @request.user == current_user
        #byebug
        @request.update(status: 'Canceled')
        flash[:notice] = I18n.t('we_ve_removed_you_from_the_list_of_requested_peo')
        # RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      else
        params[:patient_note] ||= ''
  
        Patient.create(user: current_user, request: @request, note: params[:patient_note])
  
        # RequestMailer.with(request: @request, user: current_user, note: params[:patient_note]).new_patient.deliver_now
  
        flash[:notice] = I18n.t('thanks_for_requesting_the_coaches_will_be')
        track_event 'User requested'
      end
  
      redirect_to request_path(@request)
    end
  
    def completed_patient
      #byebug
      if @request.requested_users.include?(current_user)
        #byebug
        @request.update(status: 'Completed')
        flash[:notice] = I18n.t('completed')
        #RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      end
  
      redirect_to request_path(@request)
    end

    def mark_as_unbooked
      #byebug
      set_request
      if current_user.is_coach?
        #byebug
        @request.update(status: 'Unbooked')
        flash[:notice] = I18n.t('has_been_unbooked')
        #RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      end
  
      redirect_to request_path(@request)
    end

    def mark_as_in_progress
      #byebug
      set_request
      if current_user.is_coach?
        #byebug
        @request.update(status: 'Booking in progress')
        flash[:notice] = I18n.t('is_in_progress')
        #RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      end
  
      redirect_to request_path(@request)
    end

    def mark_as_book_complete
      #byebug
      set_request
      if current_user.is_coach?
        #byebug
        @request.update(status: 'Booking completed, awaiting patient confirmation')
        flash[:notice] = I18n.t('booking_complete')
        #RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      end
  
      redirect_to request_path(@request)
    end

    def confirm_appointment
      set_request
      #byebug
      if @request.status != 'Patient Confirmed'
        updated = @request.update(status: 'Patient Confirmed')
        respond_to do |format|
          if updated
            format.html { redirect_to request_path(@request), notice: I18n.t('confirmation_success') }
            format.json { render :show, status: :ok, location: @request }
          else
            format.html { render :edit }
            format.json { render json: @request.errors, status: :unprocessable_entity }
          end
        end
        # RequestMailer.with(request: @request, user: current_user).cancel_patient.deliver_now
      end  
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_request
        @request = Request.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def request_params
        params.fetch(:request, {}).permit(:user_id, :patient_email, :f_name, :l_name, :birth_date, :phone, :address, :highlight, :city, :state, 
        :zip, :sex, :pref_language, :self_book, :closest_city, :travel_radius, :weekday_avail, :weekday_times, :weekend_avail, :weekend_times, 
        :eligibility_group, :critical_to_book_with, :book_with_full_name, :book_with_email, :book_with_phone, :open_to_same_day, :notes, :requested_by_email,
        :requested_by_name, :over_50, :status, :weekday_list => [], :weekend_list => [], :weekday_time_list => [], :weekend_time_list => [])
      end
  
      def ensure_owner_or_admin
        if !@request.can_edit?(current_user)
          flash[:error] = I18n.t('apologies_you_don_t_have_access_to_this')
          redirect_to requests_path
        end
      end
  
      def set_requests_query

app/helpers/requests_helper.rb
module RequestsHelper
  def request_row_class(request)
    if request.highlight
      'border-2 border-orange-300 bg-orange-100'
    else
      'hover:bg-gray-50 focus:outline-none focus:bg-gray-50'
    end
  end

  # def is_requests_path
  #   request.path == requests_path or request.path.include?('/requests/p') or Settings.request_categories.map(&:slug).include?(params[:category_slug]) or Settings.request_locations.map(&:slug).include?(params[:category_slug])
  # end

  def format_country(country)
    return country if country == '' || country == 'Global'

    begin
      IsoCountryCodes.find(country).name
    rescue
      # Fallback to raw value
      country
    end
  end

  def request_panel_item(title: '', &block)
    render layout: 'partials/request-panel-item', locals: {title: title} do
      capture(&block)
    end
  end
end

app/views/requests/_change_status.erb
<div class="text-center">
  <% if current_user.blank? %>
      <%= link_to new_user_registration_path do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-full text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-50 active:text-gray-800">
          <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"/>
          </svg>
          <span>
            <%= t('sign_up_to_patient') %>
          </span>
        </button>
      <% end %>
  <% else %>
    <% if current_user.requested_for_appointment?(@request) && @request.status != 'Completed' && current_user.is_patient? %>
      <%= link_to toggle_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-orange-600 hover:bg-orange-500 focus:outline-none focus:shadow-outline-orange focus:border-orange-700 active:bg-orange-700">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('cancel_request') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <%= link_to completed_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-green-900 hover:bg-green-800 focus:outline-none focus:shadow-outline-green focus:border-green-800 active:bg-green-800">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('i_have_self_booked') %>
          </span>
        </button>
      <% end %>
      <% if @request.status == 'Booking completed, awaiting patient confirmation' %>
        <br /><br />
        <%= link_to confirm_appointment_request_path(@request), method: :post do %>
          <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-700 active:bg-blue-700">
            <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
            </svg>
            <span>
              <%= t('click_to_confirm') %>
            </span>
          </button>
        <% end %>
      <% elsif @request.status == 'Patient Confirmed' %>
        <br /><br />
        <%= link_to completed_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-green-900 hover:bg-green-800 focus:outline-none focus:shadow-outline-green focus:border-green-800 active:bg-green-800">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('patient_completed') %>
          </span>
        </button>
        <% end %>
      <% end %>
    <% end %> <!--end patient options-->
    <% if current_user.is_coach? %>
      <%= link_to toggle_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-orange-600 hover:bg-orange-500 focus:outline-none focus:shadow-outline-orange focus:border-orange-700 active:bg-orange-700">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('cancel_request') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <%= link_to completed_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-gray-400 hover:bg-gray-300 focus:outline-none focus:shadow-outline-gray focus:border-gray-400 active:bg-gray-400">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('patient_self_booked') %>
          </span>
        </button>
      <% end %>
      <br /> <br />
      <%= link_to mark_as_unbooked_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:shadow-outline-red focus:border-red-700 active:bg-red-700">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('unbooked') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <%= link_to mark_as_in_progress_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-orange-400 hover:bg-orange-300 focus:outline-none focus:shadow-outline-red focus:border-orange-400 active:bg-orange-300">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('in_progress') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <%= link_to mark_as_book_complete_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-yellow-300 hover:bg-yellow-400 focus:outline-none focus:shadow-outline-yellow focus:border-yellow-400 active:bg-yellow-400">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('mark_booking_complete') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <% if @request.status == 'Booking completed, awaiting patient confirmation' %>
        <%= link_to confirm_appointment_request_path(@request), method: :post do %>
          <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-700 active:bg-blue-700">
            <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
            </svg>
            <span>
              <%= t('patient_confirm') %>
            </span>
          </button>
        <% end %>
      <% elsif @request.status == 'Patient Confirmed' %>
        <%= link_to completed_patient_request_path(@request), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-green-900 hover:bg-green-800 focus:outline-none focus:shadow-outline-green focus:border-green-800 active:bg-green-800">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('patient_completed') %>
          </span>
        </button>
        <% end %>
      <% end %>
    <% end %> <!-- end coach options -->
  <% end %>
</div>

app/views/requests/_user_avatar.html.erb
<div class="flex items-center">
  <div>
    <%= gravatar_image_tag user.email, secure: true, class: 'inline-block h-5 w-5 rounded-full inline-block align-middle' %>
  </div>
  <div class="ml-2">
    <% if user.f_name.present? && user.l_name.present? %>
      <p class="text-sm leading-5 font-medium text-gray-700 group-hover:text-gray-900 inline-block align-middle">
        <%= user.f_name %> <%= user.l_name %>
      </p>
    <% end %>
  </div>
</div>