config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :resources
  get 'hello_world', to: 'hello_world#index'
  # Redirect www to non-www.
  if ENV['CANONICAL_HOST']
    constraints(host: Regexp.new("^(?!#{Regexp.escape(ENV['CANONICAL_HOST'])})")) do
      match '/(*path)' => redirect { |params, req| "https://#{ENV['CANONICAL_HOST']}/#{params[:path]}" },  via: [ :get, :post, :put, :delete ]
    end
  end

  root 'home#index'

  get '/about', to: 'home#about', as: 'about'

  # get '/resources', to: 'home#resources', as: 'resources'

  # get '/guidelines', to: 'appointments#guidelines', as: 'guidelines'

  # get '/data/appointments',   to: 'data#appointments'
  get '/data/requests',   to: 'data#requests'
  get '/data/users',      to: 'data#users'
  get '/data/patients', to: 'data#patients'

  # get '/reports', to: "reports#index"

  get '/admin' => 'reports#index'
  # get '/admin/edit' => 'admin#edit_site', as: 'edit_site'
  # post '/admin/edit' => 'admin#edit_site'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/p/:page' => 'users/registrations#index', as: 'users_with_pagination'
    get 'users', to: 'users/registrations#index', as: 'patients'
    # get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end

  # get '/appointments/p/:page' => 'appointments#index', as: 'appointments_with_pagination'
  get '/requests/p/:page' => 'requests#index', as: 'requests_with_pagination'

  delete '/images/:resource_name/:resource_id', to: 'images#destroy'

  # resources :appointments do
  #   collection do
  #     get :requested
  #     get :own
  #   end

  #   member do
  #     post :toggle_patient
  #     post :completed_patient
  #     get :patients
  #   end
  # end

  resources :requests do
    collection do
      get :requested
      get :own
    end

    member do
      post :toggle_patient
      post :completed_patient
      post :confirm_appointment
      post :mark_as_unbooked
      post :mark_as_in_progress
      post :mark_as_book_complete
      get :patients
    end
  end

  scope 'admin' do
    post :delete_user, to: 'admin#delete_user', as: 'delete_user'
    post :toggle_highlight, to: 'admin#toggle_highlight', as: 'toggle_request_highlight'
  end


  get '/:category_slug(/p/:page)', to: 'requests#index', action: :index


end

app/views/resources/_resource_form.html.erb
<div class="mt-6 sm:mt-5">
  <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="name" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
      <%= t('provider_name') %>
    </label>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg flex rounded-md shadow-sm">
        <%= f.text_field "name", class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="description" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
      <%= t('describe_the_resource') %>
    </label>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg flex rounded-md shadow-sm">
        <%= f.text_area "description", rows: 3, class: "form-textarea block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="link" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
      <%= t('link') %>
    </label>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg flex rounded-md shadow-sm">
        <%= f.text_field "link", rows: 3, class: "form-textarea block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="username" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
      <%= t('location') %><br/>
    </label>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg flex rounded-md shadow-sm">
        <%= f.text_field "location", class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
      </div>
      <p class="mt-2 text-sm text-gray-500"><%= t('if_statewide') %></p>
    </div>
  </div>
</div>

app/views/resources/_resources-announcements.html.erb
<% Settings.events.each do |announcement| %>
  <div class="container">
    <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6 mb-4">
      <div class="-ml-4 -mt-4 flex justify-between items-center flex-wrap sm:flex-no-wrap">
        <div class="ml-4 mt-4">
          <p class="text-base leading-5 font-bold text-primary-600 tracking-tight">
            <%= announcement[:title] %>
          </p>
          <p class="mt-1 text-sm leading-5 text-gray-500">
            <%= announcement[:sub_title] %>
          </p>
        </div>
        <div class="ml-4 mt-4 flex-shrink-0">
          <span class="inline-flex rounded-md shadow-sm">
            <%= link_to announcement[:cta_url], target: "_blank" do %>
              <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:shadow-outline-primary focus:border-primary-700 active:bg-primary-700">
              <%= announcement[:cta_text] %>
              </button>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/resources/_resources-links.html.erb
<% if local_assigns[:resources] %>
  <section id="<%= local_assigns[:html_id] %>">
    <div class="container pb-8">
      <div class="px-4 sm:px-0 mt-10 mb-6 font-bold text-center">
        <%= local_assigns[:title] %>
      </div>

      <div class="mx-4 sm:mx-0 grid grid-cols-1 sm:grid-cols-2 gap-4 lg:col-gap-12">
        <% local_assigns[:resources].each do |link| %>
          <div class="flex flex-col text-center">
            <%= link_to link[:cta_url], target: '_blank', class: 'flex' do %>
              <span class="text-sm w-full items-center px-4 py-3 border border-transparent leading-5 rounded-md font-bold  bg-secondary-200 text-primary-600 hover:bg-secondary-300 focus:outline-none focus:shadow-outline-primary focus:border-secondary-300 active:bg-secondary-300 rounded-md shadow-sm">
              <%= link[:cta_text] %>
              </span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/resources/_resources.html.erb
<div class="container pb-8">
<div class="grid grid-cols-1 sm:grid-cols-2 gap-6 mt-4">
  <% @resources.each do |resource| %>
    <div class="mx-4 sm:mx-0 flex flex-col hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out shadow bg-white rounded-lg overflow-hidden">
      <div class="flex items-center justify-between space-y-top-4 space-y-bottom-4 ml-4">
          <div class="flex items-center">
            <div class="text-base leading-5 font-medium text-primary-600 truncate px-2">
              <%= resource[:name] %>
            </div>
          </div>
          <% if resource[:link] %>
            <%= link_to resource[:link], target: '_blank'  do %>
              <div class="text-sm leading-5 font-medium text-primary-600 truncate px-4 sm:px-6 mr-2">
                <%= t('apply_here') %>
                <%= inline_svg_pack_tag 'media/svgs/right-link.svg', class: 'inline-block' %>
              </div>
            <% end %>
          <% end %>
          </div>
          <hr>
          <div class="mt-2 sm:flex sm:justify-between pt-2 pb-1 px-4 sm:px-6 flex-1">
            <div class="text-sm leading-5 text-gray-500">
              <p><%= resource[:description] %></p>
            </div>
          </div>
          <div class="mt-4 sm:flex sm:justify-between px-4 pt-2 sm:px-6 pb-2 text-primary-600">
            <div class="sm:flex">
              <div class="mt-2 flex items-center text-xs leading-5 sm:mt-0">
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-primary-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"/>
                </svg>
                <%= resource.location.present? ? resource.location : 'Global' %>
              </div>
            </div>
            <div class=" flex items-center text-xs leading-5">
            <% if current_user && current_user.is_coach? %>
              <%= link_to resource_path(resource), target: '_blank'  do %>
              <div class="text-sm mr-2 px-1 leading-5 font-medium text-primary-600">
                <%= t('click_to_edit') %>
              </div>
            <% end %>
            <% end %>
            </div>
          </div>
        </div>
  <% end %>
</div>

app/views/resources/_transport.html.erb
<div class="border-2 mx-4 border-green-500 p-3">
    <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
    Transportation Resources
    </h2>
    <div align="center" class="mt-8">
      <div class="sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
          <table id="team-table" class="table-auto">
            <thead>
              <tr>
                <th colspan="4" class="bg-primary-500">
                </th>
              </tr>
              <tr>
                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-white text-center bg-primary-500">
                  Name
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-white text-center bg-primary-500">
                 Phone
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-white text-center bg-primary-500">
                Link
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-white text-center bg-primary-500">
                Description
                </td>
              </tr>
            </thead>
            <tbody>
              <% striped_classes_cycle = [ "bg-white", "bg-ltgrey-500" ] %>
                <tr class="<%= cycle striped_classes_cycle %>">
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900 text-left">
                  CAP Metro
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500 text-right">
                  512-369-6050
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap font-medium text-primary-900 hover:font-bblack hover:text-primary-700 text-sm leading-5 text-gray-500 text-left">
                  <a href="https://www.capmetro.org/vaccine-access" target="_blank">CAP Metro Vaccine Access</a>
                  </td>
                  <td class="px-6 py-4 whitespace-normal text-sm leading-5 text-gray-500 text-left">
                  <p>Call Monday-Sunday between 6 a.m. and 9 p.m. to request your trip.<br/><br/>
                  Same-day reservations are available, time permitting. 24 hour notice ideal.<br/><br/> 
                  Do not have to be registered with them, no special requirements.<br/><br/> 
                  Just have to supply name, phone number, appointment time and place, and pick up address.<br/><br/> 
                  Take appointments 7 am - 6 pm</p>
                  </td>
                </tr>
                <tr class="<%= cycle striped_classes_cycle %>">
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900 text-left">
                  Ride United
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500 text-right">
                  833-512-2289
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap font-medium text-primary-500 hover:font-bold hover:text-primary-700 text-sm leading-5 text-gray-500 text-left">
                  <a href="https://connectatx.unitedwayaustin.org/united-way-for-greater-austin--austin-tx--ride-united-covid-19-vaccine-rides/4706912557989888?postal=78702" target="_blank">ConnectATX</a>
                  </td>
                  <td class="px-6 py-4 text-sm whitespace-normal leading-5 text-gray-500 text-left">
                  <p>United Way for Greater Austin provides rides for those in need transportation to receive the COVID-19 vaccine.<br/><br/>

                    This program provides: Transportation for the COVID-19 vaccine. Clients must have a scheduled vaccination appointment(s) before they schedule a ride.<br/><br/>

                      At this time, drive-through only vaccination sites cannot be accommodated by Lyft and Lyft Codes should not be used for this purpose.<br/><br/>

              Clients must have a smartphone to download the Lyft app as well as either a credit or debit card as method of payment. Each Lyft Code allows for two one-way rides, each ride up to $25 each, scheduled or hailed directly by the Client through Lyft App. If ride costs more than $25 or the Client incurs additional fees, the Client is responsible for payment.<br/><br/>

                    Once a Client adds the Lyft Code to their Lyft App, it will automatically default to be used on the next ride the Client schedules. Clients should only add the Lyft Code when they are ready to schedule their rides to/from their vaccinations. Clients cannot schedule a personal ride first because it will apply it to that.<br/><br/>

                 Clients must comply with Lyft's Health Safety Requirements, which include wearing a face covering.<br/><br/>
  
                      Anyone under the age of 18 must be accompanied by a parent or guardian.
                    </p>
                  </td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resources/edit.html.erb
<div class="container">
  <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
    <%= form_for @resource do |f| %>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          <%= t('edit_resource_name', name: @resource.name) %>
        </h3>
        <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
          <%= t('this_information_will_be_displayed_publicly') %>
        </p>

        <%= render partial: 'resource_form', locals: { f: f } %>
      </div>
      <div class="mt-8 border-t border-gray-200 pt-5">
        <div class="flex justify-end">
          <span class="ml-3 inline-flex rounded-md shadow-sm">
            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:border-primary-700 focus:shadow-outline-primary- active:bg-primary-700 transition duration-150 ease-in-out">
              <%= t('update_resource') %>
            </button>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<%- share_title t('resources') %>


<%= render partial: 'partials/events' %>

<section class="resource-section">
  <div class="container mb-8">
    <% if current_user && current_user.is_coach? %>
    <div class="flex-shrink-0 text-center mb-6">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to new_resource_path do %>
          <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:shadow-outline-primary- focus:border-primary-700 active:bg-primary-700">
            <%= t('create_resource') %>
          </button>
        <% end %>
      </span>
    </div>
    <% end %>
  </div>

  <%= render partial: 'resources' %>

</section>

<section>
  <a id="transport"></a>
  <%= render partial: 'transport' %>
</section>

app/views/resources/new.html.erb
<div class="container">
  <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
    <%= form_for @resource do |f| %>
      <div>
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          <%= t('create_new_resource') %>
        </h3>
        <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
          <%= t('this_information_will_be_displayed_publicly') %>
        </p>
      </div>

      <%= render partial: 'resource_form', locals: { f: f } %>
      <div class="mt-8 border-t border-gray-200 pt-5">
        <div class="flex justify-end">
          <span class="ml-3 inline-flex rounded-md shadow-sm">
            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:border-primary-700 focus:shadow-outline-primary- active:bg-primary-700 transition duration-150 ease-in-out">
              <%= t('create_resource') %>
            </button>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<%- share_title "Resource #{@resource.name}" %>

<div class="container">
  <div class="bg-white px-4 py-5 border-b border-gray-200 sm:rounded-lg shadow mx-4 sm:mx-0 sm:px-6">
    <div class="-ml-4 -mt-4 flex justify-between items-center flex-wrap sm:flex-no-wrap">
      <div class="ml-4 mt-4">
        <div class="flex items-center">
          <h3 class="text-lg underline leading-6 font-medium text-gray-900">
            <%= link_to @resource.name, @resource.link, target: "_blank", rel: "nofollow" %>
          </h3>
        </div>
      </div>

      <div class="ml-4 mt-4 flex-shrink-0 flex">
        <% if current_user.is_coach? %>
          <span class="ml-3 inline-flex rounded-md shadow-sm">
            <%= link_to edit_resource_path(@resource) do %>
              <button type="button" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-50 active:text-gray-800">
                <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/>
                </svg>
                <span>
                  <%= t('edit') %>
                </span>
              </button>
            <% end %>
          </span>
          <span class="ml-3 inline-flex rounded-md shadow-sm">
            <%= link_to resource_path(resource_id: @resource.id), method: :delete, data: { confirm: "Are you sure you want to delete this resource?" } do %>
              <button type="button" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-50 active:text-gray-800">
                <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/>
                </svg>
                <span>
                  <%= t('delete') %>
                </span>
              </button>
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <br/>

  <div class="bg-white shadow overflow-hidden sm:rounded-lg mx-4 sm:mx-0">
    <div class="px-4 py-5 sm:p-0">
      <dl>
        <div class="mt-8 sm:mt-0 sm:grid sm:grid-cols-3 sm:gap-4 sm:border-t sm:border-gray-200 sm:px-6 sm:pt-5 sm:pb-2">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            <%= t('description') %>
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
            <%= simple_format @resource.description, class: 'mb-3' %>
          </dd>
        </div>
        <div class="mt-8 sm:mt-0 sm:grid sm:grid-cols-3 sm:gap-4 sm:border-t sm:border-gray-200 sm:px-6 sm:pt-5 sm:pb-2">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            <%= t('link') %>
          </dt>
          <dd class="mt-1 text-sm leading-5 text-primary-500 sm:mt-0 sm:col-span-2">
            <%= link_to nil, @resource.link, class: 'mb-3', target: "_blank", rel: "nofollow" %>
          </dd>
        </div>
        <div class="mt-8 sm:mt-0 sm:grid sm:grid-cols-3 sm:gap-4 sm:border-t sm:border-gray-200 sm:px-6 sm:py-5">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            <%= t('location') %>
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
            <%= @resource.location %>
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>