config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :resources
  get 'hello_world', to: 'hello_world#index'
  # Redirect www to non-www.
  if ENV['CANONICAL_HOST']
    constraints(host: Regexp.new("^(?!#{Regexp.escape(ENV['CANONICAL_HOST'])})")) do
      match '/(*path)' => redirect { |params, req| "https://#{ENV['CANONICAL_HOST']}/#{params[:path]}" },  via: [ :get, :post, :put, :delete ]
    end
  end

  root 'home#index'

  get '/about', to: 'home#about', as: 'about'

  # get '/resources', to: 'home#resources', as: 'resources'

  # get '/guidelines', to: 'appointments#guidelines', as: 'guidelines'

  # get '/data/appointments',   to: 'data#appointments'
  get '/data/requests',   to: 'data#requests'
  get '/data/users',      to: 'data#users'
  get '/data/patients', to: 'data#patients'

  # get '/reports', to: "reports#index"

  get '/admin' => 'reports#index'
  # get '/admin/edit' => 'admin#edit_site', as: 'edit_site'
  # post '/admin/edit' => 'admin#edit_site'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/p/:page' => 'users/registrations#index', as: 'users_with_pagination'
    get 'users', to: 'users/registrations#index', as: 'patients'
    # get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end

  # get '/appointments/p/:page' => 'appointments#index', as: 'appointments_with_pagination'
  get '/requests/p/:page' => 'requests#index', as: 'requests_with_pagination'

  delete '/images/:resource_name/:resource_id', to: 'images#destroy'

  # resources :appointments do
  #   collection do
  #     get :requested
  #     get :own
  #   end

  #   member do
  #     post :toggle_patient
  #     post :completed_patient
  #     get :patients
  #   end
  # end

  resources :requests do
    collection do
      get :requested
      get :own
    end

    member do
      post :toggle_patient
      post :completed_patient
      post :confirm_appointment
      post :mark_as_unbooked
      post :mark_as_in_progress
      post :mark_as_book_complete
      get :patients
    end
  end

  scope 'admin' do
    post :delete_user, to: 'admin#delete_user', as: 'delete_user'
    post :toggle_highlight, to: 'admin#toggle_highlight', as: 'toggle_request_highlight'
  end


  get '/:category_slug(/p/:page)', to: 'requests#index', action: :index


end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
    belongs_to :request

    acts_as_taggable_on :communications
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to request_path(@appointment.request), notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to request_path(@appointment.request), notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    set_appointment
    req = @appointment.request
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to request_path(req), notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.fetch(:appointment, {}).permit(:request_id, :reference_num, :patient_name, :provider, :address, :city, :state,
        :zip, :coach_notes, :communication_status, :communicated, :date, :time, :user_id, :booked_by_name, :booked_by_email, :communication_list => [])
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment_form.html.erb
<div>
  <div>
    <div>
      <h3 class="text-lg mt-3 leading-6 font-medium text-gray-900">
        <%= title %>
      </h3>
    </div>

    <div class="mt-6 sm:mt-5">
      <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="reference_num" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('reference_num') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :reference_num, class: "flex-1 form-input block w-full rounded-md transition duration-150 ease-in-out sm:text-sm sm:leading-5"%>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="f_name" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('patient_name')%><span class="text-red-500">*</span><br/>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :patient_name, value: (params[:f_name] + " " + params[:patient_name]), class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="provider" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('provider_name') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :provider, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
          <p class="text-sm text-gray-500">Example: Seguin H-E-B (#716)</p>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="l_name" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('provider_address') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :address, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="l_name" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('provider_city') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :city, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>


      <div class="mt-6 sm:mt-5">
        <div class="sm:border-t sm:border-gray-200 sm:pt-5">
          <fieldset>
            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
              <div>
                <legend class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700">
                  <%= t('provider_state') %><span class="text-red-500">*</span>
                </legend>
              </div>
              <div class="mt-4 sm:mt-0 sm:col-span-2">
                <div class="max-w-lg">
                    <div class="relative flex items-start">
                      <div class="absolute pb-4 flex items-center h-5">
                        <% num = 0 %>
                        <% states_array = Settings.states.map { |state| [state, state] } %>
                        <%= f.select :state, options_for_select(states_array, "Texas"), class:  "form-select h-4 w-4 text-primary-600 transition duration-150 ease-in-out" %>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="zip" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('provider_zip') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :zip, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="birth_date" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('date') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.date_field :date, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="time" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('time') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.time_field :time, class: "flex-1 form-input block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
        </div>
      </div>

      <div class="mt-6 sm:mt-5">
        <div class="sm:border-t sm:border-gray-200 sm:pt-5">
          <fieldset>
            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
              <div>
                <legend class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700">
                  <%= t('communicated') %><span class="text-red-500">*</span>
                </legend>
              </div>
              <div class="mt-4 sm:mt-0 sm:col-span-2">
                <div class="max-w-lg">
                  <div class="block">
                    <%= f.radio_button :communicated, true, class: "form-radio h-4 w-4 text-primary-600 transition duration-150 ease-in-out" %>
                    <%= f.label :communicated, t('is_yes'), value: true, class: "pl-2 text-sm text-gray-700"  %>
                  </div>

                  <div class="block">
                    <%= f.radio_button :communicated, false, class: "form-radio h-4 w-4 text-primary-600 transition duration-150 ease-in-out" %>
                    <%= f.label :communicated, "No", value: false, class: "pl-2 text-sm text-gray-700" %>
                  </div>
                </div>
              </div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 is-accepting-volunteers">
        <div class="sm:border-t sm:border-gray-200 sm:pt-5">
          <fieldset>
            <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
              <div>
                <legend class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700">
                  <%= t('communication_status') %><span class="text-red-500">*</span>
                </legend>
              </div>
              <div class="mt-4 sm:mt-0 sm:col-span-2">
                <div class="max-w-lg">
                  <% Settings.communication_statuses.each do |communication| %>
                    <div class="relative flex items-start">
                      <div class="absolute flex items-center h-5">
                        <%= f.check_box :communication_list, { multiple: true, class:  "form-checkbox h-4 w-4 text-primary-600 transition duration-150 ease-in-out"}, communication, nil %>
                      </div>
                      <div class="pl-7 text-sm leading-5">
                        <label for="weekday_list_<%= communication.downcase.gsub(' & ', '__').gsub(' ', '_') %>" class="font-medium text-gray-700">
                          <%= communication %>
                        </label>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
        <label for="booked_by_name" class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
          <%= t('booked_by_name') %><span class="text-red-500">*</span>
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
          <div class="max-w-lg flex rounded-md shadow-sm">
            <%= f.text_field :booked_by_name, class: "flex-1 form-input block w-full rounded-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", required: true %>
          </div>
          <p class="text-sm text-gray-500">Please enter your full name.</p>
        </div>
      </div>

      <div class="mt-8 border-t border-gray-200 pt-8 sm:mt-5 sm:pt-10">
        <div>
        <a id="notes"></a>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            <%= t('coach_notes') %>
          </h3>
          <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <a name="notes"></a>
              <div class="max-w-lg flex rounded-md shadow-sm">
                <%= f.text_area :coach_notes, class: "flex-1 form-textarea block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <%= f.hidden_field :request_id, :value => params[:request_id]%>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :booked_by_email, :value => current_user.email %>

      <div class="mt-8 border-t border-gray-200 pt-5">
        <div class="flex justify-end">
    <span class="ml-3 inline-flex rounded-md shadow-sm">
      <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:border-primary-700 focus:shadow-outline-primary- active:bg-primary-700 transition duration-150 ease-in-out">
        <%= cta %>
      </button>
    </span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/_project.html.erb
<li class="border-t border-gray-200">
  <div class="block transition duration-150 ease-in-out <%= appointment_row_class appointment %>">
    <div class="px-4 py-4 sm:px-6">
      <div class="flex flex-col md:flex-row md:items-center md:justify-between">
        <div class="text-sm leading-5 font-medium text-primary-600 truncate">
          <%= link_to appointment.name, appointment_path(appointment) %>
        </div>
        <div class="mt-2 md:mt-0 md:ml-4 flex-shrink-0 flex">
          <% appointment_volunteer_class = appointment.volunteered_users.count > 0 ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800" %>
          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full <%= appointment_volunteer_class %>">
            <% if appointment.accepting_volunteers? %>
              <% if appointment.volunteered_users.count == 0 %>
                <%= t('no_volunteers') %>
              <% else %>
                <%= pluralize(appointment.volunteered_users.count, t('volunteer')) %>
              <% end %>

              <% if current_user.blank? %>
                - <%= t('sign_up_to_volunteer').downcase %>
              <% elsif !current_user.has_complete_profile? %>
                - <%= t('complete_your_profile_to_volunteer').downcase %>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
      <div class="mt-2 sm:flex sm:justify-between">
        <div class="text-sm leading-5 text-gray-500">
          <%= simple_format appointment.description, class: 'mb-2' %>
        </div>
      </div>
      <% if appointment.appointment_types.present? || appointment.skills.present?  %>
        <div class="flex flex-col md:flex-row items-start justify-between">
          <div class="flex flex-col  flex-1 justify-end flex-wrap mt-2">
            <% if appointment.appointment_types.present? %>
              <div class="mt-2 text-sm leading-5 text-gray-500 sm:mt-0 font-bold">Helping with: </div>
              <div class="flex flex-row flex-wrap space-x-right-2 space-y-top-2">
                <%= skill_badges appointment.appointment_types.map(&:name), limit: 3, model: 'appointments', filter_by: 'appointment_types' %>
              </div>
            <% end %>
          </div>
          <% if appointment.skills.present? %>
            <div class="flex flex-col md:justify-end flex-wrap mt-2">
              <div class="mt-2 text-sm md:text-right leading-5 text-gray-500 sm:mt-0 font-bold">Looking for:</div>
              <div class="flex flex-row flex-wrap md:items-end md:content-end md:justify-end space-x-right-2 md:space-x-right-0 md:space-x-left-2 space-y-top-2">
                <%= skill_badges appointment.skills.map(&:name), limit: 3, color: 'blue', model: 'appointments', filter_by: 'skills' %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="mt-2 sm:flex sm:justify-between">
        <div class="sm:flex">
          <div class="mt-2 flex items-center text-sm leading-5 text-gray-500 sm:mt-0">
            <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"/>
            </svg>
            <%= appointment.volunteer_location.present? ? appointment.volunteer_location : 'Remote' %>
          </div>
        </div>
        <div class="mt-2 flex items-center text-xs leading-5 text-gray-500 sm:mt-0">
          <span>
            <%= t('created') %>
            <time><%= distance_of_time_in_words_to_now appointment.created_at %> ago</time>
          </span>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/appointments/_volunteer_button.html.erb
<div class="text-center">
  <% if current_user.blank? %>
    <% if @appointment.accepting_patients? %>
      <%= link_to new_user_registration_path do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-full text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-50 active:text-gray-800">
          <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"/>
          </svg>
          <span>
            <%= t('sign_up_to_patient') %>
          </span>
        </button>
      <% end %>
    <% end %>
  <% elsif !current_user.has_complete_profile? %>
    <% if @appointment.accepting_patients? %>
      <%= link_to edit_user_registration_path do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-full text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:bg-gray-50 active:text-gray-800">
          <span>
            <%= t('complete_your_profile_to_request') %>
          </span>
        </button>
      <% end %>
    <% end %>
  <% else %>
    <% if current_user.requested_for_appointment?(@appointment) %>
      <%= link_to toggle_patient_appointment_path(@appointment), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-orange-600 hover:bg-orange-500 focus:outline-none focus:shadow-outline-orange focus:border-orange-700 active:bg-orange-700">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('cancel_request') %>
          </span>
        </button>
      <% end %>
      <br /><br />
      <%= link_to completed_patient_appointment_path(@appointment), method: :post do %>
        <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-green-600 hover:bg-green-500 focus:outline-none focus:shadow-outline-green focus:border-green-700 active:bg-green-700">
          <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
            <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
          </svg>
          <span>
            <%= t('patient_completed') %>
          </span>
        </button>
      <% end %>
    <% else %>
      <% if !@appointment.accepting_patients %>
        <%= link_to 'javascript:void(0)', class: "not-accepting-patients" do %>
          <button id="patients-filled-btn" type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:shadow-outline-primary- focus:border-primary-700 active:bg-primary-700">
            <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
            </svg>
            <span>
              <%= t('patients_filled') %>
            </span>
          </button>
        <% end %>
      <% elsif current_user.has_correct_skills?(@appointment) %>
        <%= link_to toggle_patient_appointment_path(@appointment), class: "patient-with-skills" , "x-appointment-name": @appointment.name, "x-skills-required": @appointment.skills.join(', '), "x-org-status": @appointment.organization_status do %>
          <button id="patients-btn" type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:shadow-outline-primary- focus:border-primary-700 active:bg-primary-700">
            <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
            </svg>
            <span>
              <%= t('patient') %>
            </span>
          </button>
        <% end %>
      <% else %>
        <%= link_to edit_user_registration_path, class: "patient-without-skills", "x-skills-required": @appointment.skills.join(', ') do %>
          <button id="patients-filled-btn" type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-full text-white bg-primary-600 hover:bg-primary-500 focus:outline-none focus:shadow-outline-primary- focus:border-primary-700 active:bg-primary-700">
            <svg class="-ml-1 mr-2 h-5 w-5 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z"/>
            </svg>
            <span>
              <%= t('patient') %>
            </span>
          </button>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>