config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :resources
  get 'hello_world', to: 'hello_world#index'
  # Redirect www to non-www.
  if ENV['CANONICAL_HOST']
    constraints(host: Regexp.new("^(?!#{Regexp.escape(ENV['CANONICAL_HOST'])})")) do
      match '/(*path)' => redirect { |params, req| "https://#{ENV['CANONICAL_HOST']}/#{params[:path]}" },  via: [ :get, :post, :put, :delete ]
    end
  end

  root 'home#index'

  get '/about', to: 'home#about', as: 'about'

  # get '/resources', to: 'home#resources', as: 'resources'

  # get '/guidelines', to: 'appointments#guidelines', as: 'guidelines'

  # get '/data/appointments',   to: 'data#appointments'
  get '/data/requests',   to: 'data#requests'
  get '/data/users',      to: 'data#users'
  get '/data/patients', to: 'data#patients'

  # get '/reports', to: "reports#index"

  get '/admin' => 'reports#index'
  # get '/admin/edit' => 'admin#edit_site', as: 'edit_site'
  # post '/admin/edit' => 'admin#edit_site'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/p/:page' => 'users/registrations#index', as: 'users_with_pagination'
    get 'users', to: 'users/registrations#index', as: 'patients'
    # get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end

  # get '/appointments/p/:page' => 'appointments#index', as: 'appointments_with_pagination'
  get '/requests/p/:page' => 'requests#index', as: 'requests_with_pagination'

  delete '/images/:resource_name/:resource_id', to: 'images#destroy'

  # resources :appointments do
  #   collection do
  #     get :requested
  #     get :own
  #   end

  #   member do
  #     post :toggle_patient
  #     post :completed_patient
  #     get :patients
  #   end
  # end

  resources :requests do
    collection do
      get :requested
      get :own
    end

    member do
      post :toggle_patient
      post :completed_patient
      post :confirm_appointment
      post :mark_as_unbooked
      post :mark_as_in_progress
      post :mark_as_book_complete
      get :patients
    end
  end

  scope 'admin' do
    post :delete_user, to: 'admin#delete_user', as: 'delete_user'
    post :toggle_highlight, to: 'admin#toggle_highlight', as: 'toggle_request_highlight'
  end


  get '/:category_slug(/p/:page)', to: 'requests#index', action: :index


end

app/views/layouts/_footer.html.erb
<footer class="flex-1 bg-ltgrey-500 mt-16">
  <div class="container px-5 py-7">
    <div class="flex flex-grow flex-col sm:flex-row justify-between text-sm text-gray-800">
      <div class="float-left mt-2">
        <%= link_to "About", about_path, class: 'font-bold mr-6' %>
        <%= link_to "GitHub", "#{GITHUB_LINK}", class: 'font-bold mr-6', target: :_blank %>
      </div>
      <div class="flex flex-col sm:flex-row">
        <span class="flex sm:px-3 py-1 sm:mr-6">
          <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="22" height="22" viewBox="0 0 160.000000 164.000000" preserveAspectRatio="xMidYMid meet" class="mr-1">
            <g transform="translate(0.000000,164.000000) scale(0.100000,-0.100000)" fill="#4A5568" stroke="none">
              <path d="M214 1346 c-17 -8 -41 -27 -52 -44 -21 -29 -22 -37 -22 -482 -1 -505 -2 -493 70 -531 33 -18 67 -19 588 -19 610 0 604 -1 642 62 19 32 20 49 20 489 0 453 0 457 -22 484 -43 55 -40 55 -640 55 -442 -1 -559 -3 -584 -14z m1049 -123 c9 -6 -11 -20 -266 -193 l-197 -134 -213 144 c-260 176 -256 173 -257 182 0 8 920 9 933 1z m-734 -303 c137 -93 255 -172 263 -175 8 -3 128 72 271 170 142 97 262 173 266 170 5 -3 10 -156 10 -340 l2 -335 -541 0 -540 0 0 334 c1 298 3 346 17 346 2 0 116 -76 252 -170z"/>
            </g>
          </svg>
          <span class="text-gray-800 text-s">Contact <%= mail_to ENV['EMAIL_ADDRESS'], nil, target: :_blank, class: 'font-bold mr-6' %></span>
        </span>
        <span class="flex pt-1">
        <!---
          <a href=<%=INSTAGRAM_LINK %> target="_blank" class="mr-2">
            <svg class="mt-1" xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24" fill="#4A5568">
              <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>
          </a>
          --->
          <a href=<%= LINKEDIN_LINK %> target="_blank" class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="#4A5568" stroke="none">
            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/>
            </svg>
          </a>
          <a href=<%=FACEBOOK_LINK %> target="_blank" class="mr-2">
            <svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 160.000000 160.000000" preserveAspectRatio="xMidYMid meet">
              <g transform="translate(0.000000,160.000000) scale(0.100000,-0.100000)" fill="#4A5568" stroke="none">
                <path d="M650 1454 c-36 -7 -101 -31 -145 -53 -367 -182 -489 -647 -257 -983 92 -133 270 -252 412 -274 l40 -7 0 237 0 236 -85 0 -85 0 0 95 0 95 84 0 84 0 4 118 c4 94 9 125 26 159 26 50 80 96 131 112 42 12 150 15 200 5 l31 -6 0 -79 0 -79 -66 0 c-59 0 -68 -3 -95 -29 -28 -28 -29 -34 -29 -115 l0 -86 90 0 c65 0 90 -3 90 -12 0 -7 -5 -50 -12 -95 l-11 -83 -79 0 -78 0 0 -235 c0 -267 -8 -248 91 -219 280 82 479 349 479 644 0 257 -144 487 -375 601 -134 66 -296 86 -445 53z"/>
              </g>
            </svg>
          </a>
          <a href=<%=TWITTER_LINK %> target="_blank">
            <svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 160.000000 160.000000" preserveAspectRatio="xMidYMid meet">
              <g transform="translate(0.000000,160.000000) scale(0.100000,-0.100000)" fill="#4A5568" stroke="none">
                <path d="M988 1327 c-125 -35 -207 -146 -208 -279 0 -56 -1 -58 -27 -58 -51 0 -160 28 -236 60 -89 37 -192 107 -262 179 -27 28 -52 51 -56 51 -4 0 -15 -20 -24 -45 -13 -33 -16 -64 -13 -117 5 -80 24 -126 71 -175 35 -38 22 -44 -40 -18 -20 8 -38 14 -40 12 -2 -2 1 -28 7 -57 17 -92 72 -166 155 -208 l40 -21 -47 -1 c-51 0 -54 -4 -38 -44 24 -63 144 -156 202 -156 33 0 27 -19 -15 -43 -72 -42 -166 -69 -267 -76 l-95 -6 70 -37 c131 -68 199 -83 380 -83 183 0 248 15 386 86 247 128 428 428 429 707 0 40 5 49 59 102 33 32 65 68 71 81 11 19 10 21 -6 16 -11 -3 -43 -12 -73 -21 l-54 -15 35 37 c35 36 68 91 68 111 0 6 -21 0 -47 -13 -27 -13 -67 -30 -91 -37 -39 -11 -44 -11 -65 9 -59 56 -183 83 -269 59z"/>
              </g>
            </svg>
          </a>
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head_content.html.erb
<% title = 'Kendra\'s Covid Coaches ' %>
<% subtitle = '' %>

<link rel="apple-touch-icon" sizes="180x180" href="<%= content_for(:dynamic_fav_ico) || asset_path('favicon/apple-touch-icon.png') %>"/>
<link rel="icon" type="image/png" sizes="32x32" href="<%= content_for(:dynamic_fav_ico) || asset_path('favicon/favicon-32x32.png') %>"/>
<link rel="icon" type="image/png" sizes="16x16" href="<%= content_for(:dynamic_fav_ico) || asset_path('favicon/favicon-16x16.png') %>"/>
<link rel="shortcut icon" href="<%= content_for(:dynamic_fav_ico) || asset_path('favicon/favicon.ico') %>"/>
<meta name="theme-color" content="#020f80"/>

<meta property="og:type" content="article"/>
<meta property="og:title" content="<%= content_for(:share_title) || title %>"/>
<meta property="og:description" content="<%= content_for(:share_desc) || subtitle %>"/>
<meta property="og:url" content="<%= content_for(:share_url) || "https://kcc-web-app-rails.herokuapp.com" %>"/>
<meta property="og:site_name" content="<%= content_for(:share_title) || title %>"/>
<meta property="og:image" content="<%= content_for(:share_img) || "https://kcc-web-app-rails.herokuapp.com/share-image.png" %>"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>

<meta name="twitter:card" content="<%= content_for(:share_twitter_card_type) || "summary_large_image" %>"/>
<meta name="twitter:title" content="<%= content_for(:share_title) || title %>"/>
<meta name="twitter:description" content="<%= content_for(:share_desc) || subtitle %>"/>
<meta name="twitter:url" content="<%= content_for(:share_url) || "https://kcc-web-app-rails.herokuapp.com" %>"/>
<meta name="twitter:image" content="<%= content_for(:share_img) || "https://kcc-web-app-rails.herokuapp.com/share-image.png" %>"/>

<meta rel="canonical" content="<%= content_for(:canonical_url) || request.url %>"/>

app/views/layouts/_header.html.erb
<header>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <h2 class="text-3xl font-bold leading-tight text-gray-900">
      <%= title %>
    </h2>
  </div>
</header>

app/views/layouts/_nav.html.erb
<nav x-data="{ open: false }" class="bg-primary-500 text-white shadow-sm">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex justify-between h-16">
      <a href="/" class="border-b-2 border-transparent hover:font-medium focus:outline-none focus:font-medium transition duration-150 ease-in-out flex items-center px-2 cursor-pointer -mx-2">
        <div class="h-10 w-10 bg-center bg-no-repeat bg-cover" style="background-image: url('<%= asset_pack_path('media/images/kcc_round_logo.png') %>')"></div>
        <span class="ml-2 md:hidden lg:block">Kendra's Covid Coaches<br><div class="text-xs">Powered by City Help</div></span>
      </a>
      <div class="absolute inset-y-0 right-0 flex items-center md:hidden">
        <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
          <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
            <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-grow-0 flex-shrink-0">
        <div class="hidden sm:mr-2 md:flex">
          <%= render partial: 'layouts/nav_links', locals: { variant: 'DESKTOP' } %>
        </div>
      </div>
    </div>
  </div>
  <div :class="{'block': open, 'hidden': !open}" class="hidden md:hidden">
    <div class="pt-2 pb-3"><%= render partial: 'layouts/nav_links', locals: { variant: 'MOBILE' } %>
    </div>
  </div>
</nav>

app/views/layouts/_nav_links.html.erb
<%= link_to resources_path, class: "#{resources_nav_link_class(variant)}" do %>
  Self-Booking Resources
<% end %>

<% if current_user %>
  <div class="relative group flex">
    <%= link_to 'javascript:void(0);', class: "#{nav_link_inactive_class(variant)} hidden md:flex" do %>
      <%= t('account') %> <%= inline_svg_pack_tag 'media/svgs/chevron-right.svg', class: 'fill-current transform rotate-90' %>
    <% end %>

    <div class="md:hidden md:group-hover:flex w-full md:flex-col md:absolute md:z-30 md:nset-auto md:left-0 md:z-20 md:bg-white md:shadow-lg md:p-4 md:w-48 md:text-sm md:space-y-2 md:mt-14">
      <div>
        <%= link_to edit_user_registration_path, class: "#{profile_nav_link_class(variant)}" do %>
          <%= t('your_profile') %>
        <% end %>
      </div>
      <% if current_user.is_patient?%>
      <div>
        <%= link_to own_requests_path, class: "#{p_requested_appointments_nav_link_class(variant)}" do %>
          <%= t('requested_appointments') %>
        <% end %>
      </div>
      <% end %>
      <% if current_user.is_coach?%>
      <div>
          <%= link_to admin_path, class: "#{admin_nav_link_class(variant)}" do %>
            <%= t('dashboard') %>
          <% end %>
      </div>
      <div>
        <%= link_to own_requests_path, class: "#{c_requested_appointments_nav_link_class(variant)}" do %>
          <%= t('requests_for_patients') %>
        <% end %>
      </div>
      <div>
        <%= link_to requests_path, class: "#{c_all_requests_nav_link_class(variant)}" do %>
          <%= t('all_patient_requests') %>
        <% end %>
      </div>
      <% end %>
      <div>
        <%= link_to destroy_user_session_path, method: :delete, class: "#{logout_nav_link_class(variant)}" do %>
          <%= t('log_out') %>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user.is_coach?%>
  <div class="self-center ml-4 mt-1">
  <%= link_to new_request_path do %>
    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-primary-500 bg-white hover:bg-green-500 hover:text-white focus:outline-none focus:shadow-outline-primary focus:border-primary-700 active:bg-primary-700 flex-shrink-0 flex-grow-0">
      <%= t('create_patient_request') %>
    </button>
   <% end %>
  </div>
  <div class="self-center ml-4 mt-1 -mr-20">
  <%= link_to requests_path do %>
    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-primary-500 bg-white hover:bg-green-500 hover:text-white focus:outline-none focus:shadow-outline-primary focus:border-primary-700 active:bg-primary-700 flex-shrink-0 flex-grow-0">
      <%= t('all_patient_requests') %>
    </button>
   <% end %>
  </div>
<% end %>
<% if current_user.is_patient?%>
  <div class="self-center ml-4 mt-1 -mr-20">
  <%= link_to new_request_path do %>
    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-primary-500 bg-white hover:bg-green-500 hover:text-white focus:outline-none focus:shadow-outline-primary focus:border-primary-700 active:bg-primary-700 flex-shrink-0 flex-grow-0">
      <%= t('request_appointment') %>
    </button>
   <% end %>
  </div>
<% end %>
<% else %>
  <%= link_to new_user_registration_path, class: "#{sign_up_nav_link_class(variant)}" do %>
    <%= t('sign_up') %>
  <% end %>
  <%= link_to new_user_session_path, class: "#{login_nav_link_class(variant)}" do %>
    <%= t('log_in') %>
  <% end %>
<% end %>

app/views/layouts/_resource_previous_events.html.erb
<div class="mx-4 sm:mx-0 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
  <% Settings.events.each do |event| %>
    <div class="flex flex-col justify-between shadow bg-white rounded-lg overflow-hidden">
      <div class="p-4">
        <div class="flex justify-between">
          <div class="font-bold text-sm text-primary-600 mb-2 leading-tight"><%= event[:title] %></div>
        </div>
        <div class="text-sm text-gray-500 leading-tight"><%= event[:sub_title].html_safe %></div>
      </div>

      <div class="text-center mb-4">
        <%= link_to event[:cta_url], target: '_blank' do %>
          <span class="text-xs relative inline-flex items-center px-4 py-2 border border-transparent leading-5 rounded-md font-bold  bg-secondary-200 text-primary-600 hover:bg-secondary-300 focus:outline-none focus:shadow-outline-primary focus:border-secondary-300 active:bg-secondary-300 rounded-md shadow-sm">
            <%= event[:cta_text] %>
          </span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_resource_upcoming_events.html.erb
<% Settings.upcoming_events.each do |event| %>
  <div class="mx-4 sm:mx-0 flex flex-wrap mb-6 text-sm rounded-lg shadow overflow-hidden">
    <div class="w-full sm:w-1/12 text-center px-4 py-2 text-white bg-primary-600 font-bold">
      <div class="flex sm:flex-col items-center justify-center h-full">
        <span class="block"><%= event[:month] %></span>
        <span class="block ml-1 sm:text-xl sm:mt-2"><%= event[:day] %></span>
      </div>
    </div>

    <div class="w-full sm:w-9/12 bg-secondary-100 py-4 px-4">
      <div class="text-gray-900 font-bold">
        <%= event[:title].html_safe %>
      </div>

      <div class="text-gray-800 pt-2">
        <%= event[:sub_title].html_safe %>
      </div>
    </div>

    <div class="w-full sm:w-2/12 bg-white py-4 px-4 text-center">
      <div class="text-primary-600 font-bold">
        <%= event[:time] %>
      </div>

      <% if event[:link] %>
        <div class="mt-3">
          <%= link_to event[:link], target: '_blank' do %>
            <span class="text-xs relative inline-flex items-center px-4 py-2 border border-transparent leading-5 rounded-md font-bold  bg-secondary-200 text-primary-600 hover:bg-secondary-300 focus:outline-none focus:shadow-outline-primary focus:border-secondary-300 active:bg-secondary-300 rounded-md shadow-sm">
              <%= event[:link_text] %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for(:share_title).present? ? content_for(:share_title)+' | ' : '' %> Kendra's Covid Coaches</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/head_content' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_tag do %>
      I18n.locale = '<%= I18n.locale %>';
    <% end %>

    <%= javascript_pack_tag "translations/#{I18n.locale}" %>
    <%= javascript_pack_tag 'hello-world-bundle' %>

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.0.1/dist/alpine.js" defer></script>
    <link href="https://fonts.googleapis.com/css2?family=<%= Settings.google_fonts_request %>&display=swap" rel="stylesheet">

      <script async src="https://www.googletagmanager.com/gtag/js?id=<%= google_analytics_id %>"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '<%= google_analytics_id %>');
        <%= track_ga_event_if_needed %>
      </script>
  </head>

  <body class="flex flex-col min-h-screen h-full antialiased <%= @bg_color %>">
    <div class="flex-1">
      <div class="pb-10 header">
        <%= render partial: 'layouts/nav' %>
      </div>

      <%= render partial: "partials/global-announcements" if @show_global_announcements %>

      <main class="flex-grow">
        <% if flash.present? %>
          <div class="container bg-ltgrey-500">
            <% flash.each do |type, msg| %>
              <div class="mb-14 <%= alert_container_class_for_flash_type type %>" role="alert">
                <span class="block sm:inline"><%= msg %></span>
              </div>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </main>
    </div>

    <%= render partial: 'layouts/footer' %>
    <%= render partial: 'partials/modal' %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>